ARG BUN_VERSION=1.3.4

FROM oven/bun:${BUN_VERSION}-alpine
WORKDIR /build

RUN apk add --no-cache curl

COPY . .
RUN bun install --frozen-lockfile
RUN bun run build:packages

WORKDIR /build/services/social-service

EXPOSE 5011

CMD ["bun", "run", "dev"]
