FROM oven/bun:1-alpine

# Set working directory
WORKDIR /build

# Copy workspace files
COPY package.json bun.lockb turbo.json ./
COPY packages ./packages
COPY apps/web ./apps/web

# Install dependencies & Build packages
RUN bun install --frozen-lockfile && bun run build:packages

WORKDIR /build/apps/web

# Expose the port the app runs on
EXPOSE 5173

# Start the development server
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]