export const paths = {
    HOME: "/home",
    SIGNIN: "/sign-in",
    SIGNUP: "/sign-up",
    PLAYLIST__TITLE__ID: "/playlist/:title/:id",
    ALBUM__TITLE__ID: "/album/:title/:id",
    WEEKRANK__TITLE__ID: "/week-chart/:title/:id",
    ZING_CHART: "/chart",
    MY_MUSIC: "/me/songs",
    FOLLOW: "follow",
    SEARCH: "search",
    SEARCH_ALL: "all",
    SEARCH_SONG: "song",
    SEARCH_PLAYLIST: "playlist",
    SEARCH_ARTIST: "artist",
    SEARCH_MV: "video",
    ARTIST__NAME: "/artist/:name",
    VIDEOCLIP__TITLE__ID: "/video-clip/:title/:id",
    ME: "/me",
    UPLOAD_MUSIC: "/me/upload-music",
}