apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-app-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-app-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-gateway-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-gateway-dev
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-home-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-home-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-song-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-song-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-notification-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-notification-dev
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-video-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-video-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-social-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-social-dev
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-auth-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-auth-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-artist-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-artist-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-banner-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-banner-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-playlist-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-playlist-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yukikaze-player-user-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yukikaze-player-user-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
