// Fake song array for testing
export const FAKE_SONGS = [
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },

    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_001',
        title: 'Summer Breeze',
        alias: 'summer-breeze',
        artistNames: 'John Doe, Jane Smith',
        releaseDate: '2024-06-15',
        duration: 245,
        size: 5242880,
        stream: 'https://example.com/audio/summer-breeze.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-06-15').toDateString(),
        updatedAt: new Date('2024-06-15').toDateString(),
    },
    {
        id: 'song_test_002',
        title: 'Midnight Dreams',
        alias: 'midnight-dreams',
        artistNames: 'Alex Johnson',
        releaseDate: '2024-07-20',
        duration: 198,
        size: 4718592,
        stream: 'https://example.com/audio/midnight-dreams.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: false,
        userId: 'user_test_002',
        createdAt: new Date('2024-07-20').toDateString(),
        updatedAt: new Date('2024-07-20').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    },
    {
        id: 'song_test_003',
        title: 'Electric Soul',
        alias: 'electric-soul',
        artistNames: 'The Rhythm Makers',
        releaseDate: '2024-08-10',
        duration: 312,
        size: 7340032,
        stream: 'https://example.com/audio/electric-soul.mp3',
        thumbnail: '/assets/default/default-song-thumbnail.png',
        hasLyrics: true,
        userId: 'user_test_001',
        createdAt: new Date('2024-08-10').toDateString(),
        updatedAt: new Date('2024-08-10').toDateString(),
    }
]

