ARG BUN_VERSION=1.3.4

FROM oven/bun:${BUN_VERSION}-alpine AS bun

FROM node:22-alpine
WORKDIR /build

RUN apk add --no-cache curl
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun

COPY . .
RUN bun install --frozen-lockfile
RUN bun run build:packages

WORKDIR /build/services/notification-service

EXPOSE 5009

CMD ["bun", "run", "dev"]
