FROM node:22-alpine

# Set working directory
WORKDIR /api

COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Start the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]